// @keepTs
// @ts-nocheck
export declare class CodeHighlight {
    keyword: ResourceColor;
    method: ResourceColor;
    type: ResourceColor;
    modifier: ResourceColor;
    constant: ResourceColor;
    variable: ResourceColor;
    operator: ResourceColor;
    punctuation: ResourceColor;
    brace: ResourceColor;
    bigBrace: ResourceColor;
    string: ResourceColor;
    number: ResourceColor;
    boolean: ResourceColor;
    nullish: ResourceColor;
    promise: ResourceColor;
    tag: ResourceColor;
    attrName: ResourceColor;
    attrValue: ResourceColor;
    doctype: ResourceColor;
    comment: ResourceColor;
    decorator: ResourceColor;
    component: ResourceColor;
    normal: ResourceColor;
}
