//
//  NearbyNoLetViewModel.swift
//  NoLet
//
//  Created by AI Assistant on 2023/7/1.
//
// Note: This file contains code automatically generated by AI.
// Usage reminder: Review carefully and thoroughly test before integration or release.

import Foundation
import Combine
import SwiftUI

class NearbyNoLetViewModel: ObservableObject {
    // 管理器实例
    private let manager = NearbyNoLetManager()
    
    // 发布属性
    @Published var nearbyPeers: [NearbyPeer] = []
    @Published var messages: [NearbyMessage] = []
    @Published var isActive: Bool = false
    
    // 订阅取消令牌
    private var cancellables = Set<AnyCancellable>()
    
    init() {
        // 订阅管理器的发布属性
        manager.$nearbyPeers
            .receive(on: RunLoop.main)
            .sink { [weak self] peers in
                self?.nearbyPeers = peers
            }
            .store(in: &cancellables)
        
        manager.$messages
            .receive(on: RunLoop.main)
            .sink { [weak self] messages in
                self?.messages = messages
            }
            .store(in: &cancellables)
        
        manager.$isActive
            .receive(on: RunLoop.main)
            .sink { [weak self] isActive in
                self?.isActive = isActive
            }
            .store(in: &cancellables)
    }
    
    // 开始发现附近设备
    func startDiscovery() {
        manager.startDiscovery()
    }
    
    // 停止发现
    func stopDiscovery() {
        manager.stopDiscovery()
    }
    
    // 刷新附近设备
    func refreshNearbyPeers() {
        manager.refreshNearbyPeers()
    }
    
    // 连接到指定设备
    func connectToPeer(_ peer: NearbyPeer) {
        manager.connectToPeer(peer)
    }
    
    // 发送消息
    func sendMessage(_ message: String, to peer: NearbyPeer) {
        manager.sendMessage(message, to: peer)
    }

    // 群聊：向所有已连接的设备群发消息
    func sendGroupMessage(_ message: String) {
        manager.sendGroupMessage(message)
    }

    // 群聊：发送图片
    func sendGroupImage(_ imageData: Data) {
        manager.sendGroupImage(imageData)
    }

    // 群聊：发送文件
    func sendGroupFile(url: URL) {
        manager.sendGroupFile(url)
    }
}