//
//  NearbyNoLetItem.swift
//  NoLet
//
//  Author:        Copyright (c) 2024 QingHe. All rights reserved.
//  Document:      https://wiki.wzs.app
//  E-mail:        to@wzs.app
//
//
//  Created by AI Assistant on 2023/7/1.
//
// Note: This file contains code automatically generated by AI.
// Usage reminder: Review carefully and thoroughly test before integration or release.

import SwiftUI
import MultipeerConnectivity

struct NearbyNoLetItem: View {
    let peer: NearbyPeer
    
    var body: some View {
        HStack {
            // 设备图标
            ZStack {
                Circle()
                    .fill(peer.isConnected ? Color.green.opacity(0.2) : Color.blue.opacity(0.2))
                    .frame(width: 50, height: 50)
                
                Image(systemName: peer.isConnected ? "person.fill" : "person")
                    .font(.system(size: 24))
                    .foregroundColor(peer.isConnected ? .green : .blue)
            }
            
            // 设备信息
            VStack(alignment: .leading, spacing: 4) {
                Text(peer.peerID.displayName)
                    .font(.headline)
                
                Text(peer.isConnected ? "已连接" : "可连接")
                    .font(.subheadline)
                    .foregroundColor(peer.isConnected ? .green : .secondary)
            }
            .padding(.leading, 8)
            
            Spacer()
            
            // 连接状态指示器
            Image(systemName: peer.isConnected ? "link" : "link.badge.plus")
                .foregroundColor(peer.isConnected ? .green : .blue)
                .font(.system(size: 18))
        }
        .padding(.vertical, 8)
        .contentShape(Rectangle())
    }
}

// 预览
struct NearbyNoLetItem_Previews: PreviewProvider {
    static var previews: some View {
        Group {
            NearbyNoLetItem(peer: NearbyPeer( peerID: MCPeerID(displayName: "iPhone 13"), isConnected: true))
            NearbyNoLetItem(peer: NearbyPeer( peerID: MCPeerID(displayName: "iPad Pro"), isConnected: false))
        }
        .previewLayout(.sizeThatFits)
        .padding()
    }
}
