// @keepTs
// @ts-nocheck
import { TreeNode } from '../model/TreeNode';
/**
 * ParagraphRender need use
 * @param data
 */
@Builder
export declare function SpanRenderBuilder(y2: string, z2: string, a3: ESObject, b3: UIContext, c3?: number, d3?: TreeNode): void;
/**
 * 根文本渲染
 * @param data 节点数据
 * @param baseType 根节点类型
 */
@Builder
export declare function BaseSpanRenderBuilder(q2: string, r2: ESObject, s2?: TreeNode): void;
