// @keepTs
// @ts-nocheck
export declare const TEXT_SELECTION_ACTION_ITEM_WIDTH: number;
export declare const TEXT_SELECTION_ACTION_BAR_HORIZONTAL_PADDING: number;
export declare const TEXT_SELECTION_ACTION_BAR_EDGE_INSET: number;
export declare function getTextSelectionActionBarWidth(t121: number, u121: number): number;
export declare function getTextSelectionActionBarX(n121: number, o121: number, p121: number): number;
export declare function shouldScrollTextSelectionActionBar(l121: number, m121: number): boolean;
